language: c

install:

    # install make
    - sudo apt-get update -qq
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 travis-tool.sh
    - BOOTSTRAP_PANDOC="1" ./travis-tool.sh bootstrap

    # check to see if pandoc is there
    - pandoc --version
    - which pandoc

    # install Rmarkdown (from HEAD)
    - echo 'options(repos=c("http://cran.us.r-project.org")); install.packages("devtools")' | sudo R --vanilla --slave
    - echo 'library(devtools); install.packages("rmarkdown")' | sudo R --vanilla --slave

    # TODO: install R project dependencies using Packrat or something

script: make
